language: php
php:
  - 5.5
  - 5.4
  - 5.3

services:
  - rabbitmq

env:
  global:
    - secure: "IK8Ys/6krzMemuwPinClNeyVj7ATYYiqYPkqcMrEpmJgNqQmwumaDFIlEyZnIc2+AlhqZjxyksX5yilTT6uXLsKhjHzM3aeb+dy3yie+9Xu8nAuexRLQxbghc2oyS7BpOx26qySmHrFNlxD0BpCD+Qa95wdwNA+IeKUDFyUx/LU="
    - secure: "JK+1029wPW6pg0Ry53leFQaz33dmCkEs48tniU8MQB1hhRezSKtfB4kQkP/XKYNzovPwGoFmwdtDz4GowDs5P0/woqi4XzO2IPZwzDqNRvNRwg68UQmgjahzkG3fAthTzrYx+JQpFlwfoVI77RVAjdP3j1+pupCDA91GIs2DtUs="

script: phpunit -v --coverage-clover=coverage.clover

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - sudo beanstalkd -d -l 127.0.0.1 -p 11300
  - sudo rabbitmqctl add_vhost queue_vhost
  - sudo rabbitmqctl add_user queue_user queue_pass
  - sudo rabbitmqctl set_permissions -p queue_vhost queue_user ".*" ".*" ".*"
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer install --dev --prefer-source

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    webhooks:
        secure: "WAiPtlSj+7PU4w26TvOstBJyHrAJ30B/bZxvW/LD0e3iaEzdS6GJNReH/o+zZrUJgnHB4bu+Kn/rEMlCFUPAGPLDK7uU1HCHe7LDPzPJdWwo8gFZoy0wu1ZPuKzApZddb7Z4Nhzgsax3YwtRK5pkqX5FOl1WOPw3hFSslZrr0mc="
